Back out "vendor abomonation with smallvec support"
ca851e8 caused compilation errors for me when running the oss build.

```sh
$ make -j oss

SAPLING_OSS_BUILD=true HGNAME=sl \
	  /usr/local/bin/python3.8 setup.py  \
	  build_py -c -d . \
	  build_clib  \
	  build_ext  -i \
	  build_rust_ext -i -l --debug \
	  build_pyzip -i \
	  build_mo
setup.py:1720: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
#...
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/zstdelta/Cargo.toml: version requirement `2.0.1+zstd.1.5.2` for dependency `zstd-sys` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
error: failed to select a version for `abomonation`.
    ... required by package `dag-types v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/dag/dag-types)`
    ... which satisfies path dependency `dag-types` (locked to 0.1.0) of package `edenapi_types v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/edenapi/types)`
    ... which satisfies path dependency `edenapi_types` (locked to 0.1.0) of package `edenapi v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/edenapi)`
    ... which satisfies path dependency `edenapi` (locked to 0.1.0) of package `repo v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/repo)`
    ... which satisfies path dependency `repo` (locked to 0.1.0) of package `clidispatch v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/clidispatch)`
    ... which satisfies path dependency `clidispatch` (locked to 0.1.0) of package `hgmain v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/exec/hgmain)`
versions that meet the requirements `^0.7` (locked to 0.7.3) are: 0.7.3

the package `dag-types` depends on `abomonation`, with features: `smallvec` but `abomonation` does not have these features.


failed to select a version for `abomonation` which could resolve this conflict
error: compilation of Rust target 'conch_parser' failed
make: *** [oss] Error 1
```

reproduction steps:
1. versions
  - macOS 13.1
  - cargo 1.65.0
2. goto any commit in ca851e8c::1a5756ce2
3. `(cd eden/scm && make oss)`

Please let me know if you need any other info for reproduction

I'd be happy to work on another solution than just reverting this changeset if
you'd rather.

Test Plan:
- originally found with `sl bisect`
- manually confirmed `ca851e~1` builds and `ca851e` does not
- confirmed backing out ca851e worked by running `cd eden/scm && make oss`

Original commit changeset: ca851e8c179f