Back out "vendor abomonation with smallvec support"
ca851e8 caused compilation errors for me when running the oss build.

```sh
make -j oss
SAPLING_OSS_BUILD=true HGNAME=sl \
	  /usr/local/bin/python3.8 setup.py  \
	  build_py -c -d . \
	  build_clib  \
	  build_ext  -i \
	  build_rust_ext -i -l --debug \
	  build_pyzip -i \
	  build_mo
setup.py:1720: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  xcode4 = xcode_version.startswith("Xcode") and StrictVersion(
setup.py:1722: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) >= StrictVersion("4.0")
Packaging assets into /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/build/edenscmdeps3.zip
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/exec/hgmain/Cargo.toml
workspace: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/edenscmnative/bindings/Cargo.toml
workspace: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/edenscmnative/bindings/modules/pythreading/Cargo.toml
workspace: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/Cargo.toml
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/configerator/structs/scm/hg/hgclientconf/Cargo.toml: version requirement `0.0.1+unstable` for dependency `fbthrift` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/edenscmnative/bindings/modules/pyzstd/Cargo.toml: version requirement `0.11.1+zstd.1.5.2` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/edenscmnative/bindings/modules/pyzstd/Cargo.toml: version requirement `5.0.1+zstd.1.5.2` for dependency `zstd-safe` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/thrift-types/Cargo.toml: version requirement `0.0.1+unstable` for dependency `fbthrift` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/fs/config/Cargo.toml: version requirement `0.0.1+unstable` for dependency `fbthrift` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/http-client/Cargo.toml: version requirement `0.11.2+zstd.1.5.2` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/config/loader/Cargo.toml: version requirement `0.11.2+zstd.1.5.2` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/hgcommands/Cargo.toml: version requirement `0.11.2+zstd.1.5.2` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/fs/service/Cargo.toml: version requirement `0.0.1+unstable` for dependency `fbthrift` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/zstdelta/Cargo.toml: version requirement `2.0.1+zstd.1.5.2` for dependency `zstd-sys` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
error: failed to select a version for `abomonation`.
    ... required by package `dag-types v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/dag/dag-types)`
    ... which satisfies path dependency `dag-types` (locked to 0.1.0) of package `edenapi_types v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/edenapi/types)`
    ... which satisfies path dependency `edenapi_types` (locked to 0.1.0) of package `edenapi v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/edenapi)`
    ... which satisfies path dependency `edenapi` (locked to 0.1.0) of package `repo v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/repo)`
    ... which satisfies path dependency `repo` (locked to 0.1.0) of package `clidispatch v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/lib/clidispatch)`
    ... which satisfies path dependency `clidispatch` (locked to 0.1.0) of package `hgmain v0.1.0 (/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/exec/hgmain)`
versions that meet the requirements `^0.7` (locked to 0.7.3) are: 0.7.3

the package `dag-types` depends on `abomonation`, with features: `smallvec` but `abomonation` does not have these features.


failed to select a version for `abomonation` which could resolve this conflict
error: compilation of Rust target 'conch_parser' failed
make: *** [oss] Error 1
```

I'd be happy to work on another solution than just reverting this changeset if
you'd rather.

Original commit changeset: ca851e8c179f